### ISSUE TITLE
Build Fails for Duplicatesdetector

### ISSUE THREAD

**Issue by ergodaveh** [AddictedCS/soundfingerprinting.duplicatesdetector#4]
Just cloned this project and the build fails

 Unable to find version '3.1.0-beta' of package 'SoundFingerprinting'.	SoundFingerprinting.DuplicatesDetector

**Comment by AddictedCS** [comment]
Yeah, this is still in progress, will update NuGet shortly.

**Comment by AddictedCS** [comment]
Fixed.
